#!/usr/bin/env sh

echo "rune operates on single word input"
./runes "test"
echo ""
echo "rune operates on multi word input"
./runes "testing multi line strings"
echo ""
echo "echo single word into runes"
echo "test" | ./runes
echo ""
echo "echo multi word input into runes"
echo "testing multi word input" | ./runes
echo ""
echo "testing runes operating on a file should return 8 lines"
./runes ./tests/sampledata
echo ""
echo "testing cat pipe file into runes should return 8 lines"
cat ./tests/sampledata | ./runes
